flow/views.py
# todo: remove unnecessary imports
from django import forms
from django.contrib import auth
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.contrib.comments.views.comments import post_comment
from django.contrib.comments.models import Comment
from django.contrib.comments.views import moderation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.core.serializers import serialize, deserialize
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseForbidden, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.loader import render_to_string
from django.template import Context, Template, RequestContext
from django.utils.html import escape
from django.utils.http import urlquote
from django.utils.safestring import mark_safe

from django.conf import settings
from flow import models
from multisite.models import current_site, users_on_site

import os, datetime, re
#import Stemmer
import urllib, minjson, tc

ALL_VIDEOS_PLAYLIST = {
'name':  '',
	'path': 'all',
	'published': False,
	'get_url': '/all/',
	'no_settings': True,
	'medias': [],
}

STOPWORDS = [
	"i", 
	"a",
	"about",
	"an",
	"are",
	"as",
	"at",
	"be",
	"by",
	"com",
	"de",
	"en",
	"for",
	"from",
	"how",
	"in",
	"is",
	"it",
	"la",
	"of",
	"on",
	"or",
	"that",
	"the",
	"this",
	"to",
	"was",
	"what",
	"when",
	"where",
	"who",
	"will",
	"with",
	"und",
	"the",
	"www",
]

def form_get_tc(form_data, id):
	return form_data[id+'_tc']
	
def form_get_bool(form_data, id):
	if form_data.has_key(id): return True
	return False

def form_get_size(form_data, id):
	t = form_data[id+'_size'];
	if t == 'custom': return '%sx%s' % (form_data[id+'_width'], form_data[id+'_height'])
	return t

def feed(request, playlist=None):
	playlist = get_object_or_404(models.Playlist, path=playlist)
	playlist.sync()
	r = render_to_response(
		'feed.html',
		{
			'playlist': playlist,
			'medias': playlist.media_set.all().order_by('-pub_date'),
		},
		context_instance = RequestContext(request),
	)
	r['Content-Type'] = 'text/xml; charset-utf-8'
	return r

def delete_playlist(request):
	id = request.GET['id']
	models.Playlist.on_site.get(id=id).delete()
	return HttpResponseRedirect('/')

def delete_clip(request):
	clip_id = request.POST['clip_id']
	models.Clip.on_site.get(id=clip_id).delete()
	return HttpResponse('')

def save_clip(request):
	clip_id = request.POST.get('clip_id', '')
	if clip_id:
		clip = models.Clip.on_site.get(id=clip_id)
	else:
		clip = models.Clip(media=models.Media.on_site.get(id=request.POST['media_id']))
	clip.start = request.POST['start']
	clip.text = request.POST['text']
	clip.save()
	return HttpResponse(str(clip.id))

def logout(request):
	recent_media = request.session.get('recent_media', [])
	auth.logout(request)
	request.session['recent_media'] = recent_media
	return HttpResponseRedirect('/signin')

def get_thumb(request):
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')
	
	media = models.Media.objects.get(id=request.GET['media_id'])
	offset = request.GET['offset']

	#thumbfn = models.Media.path('thumb', models.Media.randStr(media.playlist, media.name)+'.jpg')
	thumbfn = media.tempBasename('thumb', '.jpg')
	fn = thumbfn.replace('thumb', 'thumb32', 1)
	models.Media.ffmpegImageGrab(media.get_file_path(), os.path.join(settings.UPLOAD_ROOT, fn), (32,24), offset)
	fn = thumbfn.replace('thumb', 'thumb64', 1)
	models.Media.ffmpegImageGrab(media.get_file_path(), os.path.join(settings.UPLOAD_ROOT, fn), (64,48), offset)
	
	return HttpResponse(settings.UPLOAD_URL + fn)

def download_encode(request):
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')
	media_id = request.GET['media_id']
	media = models.Media.objects.get(id=media_id)
	cmd = media.download_encode()
	return HttpResponse(cmd)

# If user requested login, try to log them in
def login(request):
	user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
	if user is not None:
		if user.is_active:
			auth.login(request, user)
		else:
			# disabled user account
			pass
	else:
		# invalid login
		return HttpResponseRedirect(request.POST.get('redirect', '/') + '?error=login')
		pass
	return HttpResponseRedirect(request.POST.get('redirect', '/'))

def watch_it(request):
	return HttpResponseRedirect('/%s' % request.POST['media'])
	
def delete_comment(request):
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')
	comment_id = request.GET['comment_id']
	moderation.delete(request, comment_id)
	#try:
	#	comment = Comment.objects.get(id=comment_id)
	#except Comment.DoesNotExist:
	#	return HttpResponseNotFound("<h1>Comment not found</h1>")
	#comment.delete()
	#return HttpResponse(comment_id)
	return HttpResponseRedirect(request.GET['redirect'])

def session_set(request):
	request.session[request.GET['name']] = request.GET['value']
	return HttpResponse(request.GET['name']+'='+request.session[request.GET['name']])

def remove_edl(request):
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')
	media = models.Media.objects.get(id=request.GET['media_id'])
	media.edl = ''
	media.timecode_display = settings.TC_TRACKS[0][0]
	media.save()
	return HttpResponse('edl removed')

def media_fullscreen(request, media):
	player_settings = {
		'url': media.get_file_url(),
		'width': '100%',
		#'height': media.get_display_height(320),
		#'height': '100%',
		'controller': 'true',
		'bgcolor': '#000000',
		'autoplay': 'false',
		'scale': 'aspect',
		'timecode': media.displaytc,
	}
	return render_to_response(
		'fullscreen.html',
		{
			'media': media,
			'player_settings': player_settings,
		},
		context_instance = RequestContext(request),
	)
	
def comment_preview(request):
	media_id = request.POST['target'].split(':')[1]
	media = models.Media.objects.get(id=media_id)
	comment = {
		'person_name': request.POST['person_name'],
		'comment': tc.parse_offsets(request.POST['comment'], media),
		'delete_able': False,
		'submit_date': datetime.datetime.now(),
		'is_preview': True,
		'media': media,
	}
	return render_to_response(
		'comment.html',
		{
			'comment': comment,
		},
		context_instance = RequestContext(request),
	)

#def post_comment(request):
	#post_comment(request)
	#target, person_name = request.POST['target'], request.POST['person_name']
	#content_type_id, object_id = target.split(':')
	#comment = Comment.objects.filter(person_name=person_name, content_type=content_type_id, object_id=object_id).order_by('-submit_date')[0]
	#if request.user.is_staff: comment.delete_able = True
	#media = models.Media.objects.get(id=object_id)
	#comment.comment = tc.parse_offsets(comment.comment, media)
	#return render_to_response('comment.html', {
	#	'comment':comment,
	#	'media': media,
	#})

def save_playlist(request):
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')

	playlist = models.Playlist.objects.get(id=request.POST['playlist_id'])
	playlist.published = form_get_bool(request.POST, 'published')
	playlist.save()

def search(request, query):
	results = []
	tapes = []
	stopped = []
	phrases = []
	#stem = Stemmer.Stemmer('english')
	stems = []
	if query and request.user.is_staff:
		phrases = re.compile('((?:\w+)|(?:".+"))').findall(query)
		for i in range(len(phrases)):
			if phrases[i] in STOPWORDS:
				stopped.append(phrases[i])
				phrases[i] = ''
				continue
			if re.compile('\w+').match(phrases[i]):
				#stems.append(stem.stemWord(phrases[i]) + "*")
				pass
		for i in range(phrases.count('')): phrases.remove('')
		phrases.extend(stems)
		fts_query = " OR ".join(phrases)
		for result in models.search(fts_query, request.user):
			media = models.Media.objects.get(id=result[0])
			clip = models.Clip.objects.get(id=result[1])
			def qparser(match):
				return '<b>%s</b>' % match.group(0)
			def wparser(match):
				return match.group(0)[0] + '<b>%s</b>' % match.group(1)
			words = []; quotes = []
			for phrase in phrases:
				if phrase[0] == '"':
					quotes.append(phrase[1:-1])
				words.append(phrase[:-1])
			clip.bolded_text = escape(clip.get_text())
			if quotes: clip.bolded_text = re.sub(re.compile('(%s)' % '|'.join(quotes), re.I), qparser, clip.get_text())
			if words: clip.bolded_text = re.sub(re.compile('\W((?:%s)\w*)' % '|'.join(words), re.I), wparser, " "+clip.bolded_text)
			results.append( {'media':media, 'clip':clip} )
	
	if query:
		medias = models.Media.objects.filter( Q(name__icontains=query)|Q(title__icontains=query)|Q(description__icontains=query) )
		medias = medias.exclude(name='__default__')
		medias = medias.filter(playlists__in=request.user.playlists)
		for media in medias: media.url = media.db_url()
	
	return render_to_response(
		'search.html',
		{
			'medias':medias,
			'results':results,
			'stopped':stopped,
			'phrases':phrases,
			'request':request,
		},
		context_instance = RequestContext(request),
	)

def save_media(request):
	
	if not request.user.is_staff: return HttpResponseForbidden('<h1>Forbidden</h1>')
	
	media = models.Media.objects.get(id=request.POST['media_id'])
	media.title = request.POST['title']
	media.description = request.POST['description']
	media.starttc = form_get_tc(request.POST, 'start')
	media.displaytc = form_get_bool(request.POST, 'display_tc')
	media.displaysize = form_get_size(request.POST, 'display')
	media.display_comments = form_get_bool(request.POST, 'display_comments')
	media.thumb = request.POST['thumb_file'].replace('thumb64', 'thumb', 1)
	
	if request.FILES.has_key('edl_file'):
		media.importEDL(request.FILES['edl_file']['content'], request.FILES['edl_file']['filename'])
	
	media.save()
	
	# to do: thumb clean up, maybe use cron jobs to clean up

flow/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load flow_extras %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>{% block title %}{{ site.info.title }}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}flow/css/style.css" />

<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}flow/themes/{{ site.info.theme }}/style.css" />

<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/prototype.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/script.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/tc.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/qtobject.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/AC_Quicktime.js"></script>
{% block head %}{% endblock %}
</head>

<body id="body">

{% block body %}

{% block sidebar %}
<div id="leftcontent" switch="sidebar_switch">
<div id="logo">{{ site.info.logotext|marksafe }}</div>
{% playlist_list %}
{% recently_watched %}

</div>
<a id="sidebar_switch" class="switch" status="{% get_attribute request "sidebar_switch" "" "show hide" %}" switch="sidebar_switch"></a>
{% endblock %}

<div id="centercontent" switch="sidebar_switch">
<div id="header">
{% header %}
</div>
{% block content %}{% endblock %}
<div id="footer">
{% block footer %}{% endblock %}
{% for query in sql_queries %}
<!--<p>{{ query.sql }} : {{ query.time }}</p>-->
{% endfor %}
</div>
</div>

<script type="text/javascript">// <![CDATA[
initSwitch();
//]]></script>

{% endblock %}

</body>
</html>

flow/templates/drop_menu.html
{% load flow_extras %}
<a class="menu_trigger" content_id="{{ content_id }}">{{ title }}</a>
<div id="{{ content_id }}" style="display:{% get_attribute request content_id 'display' 'block' %};" class="content">

flow/templates/footer.html
<p id="legal">Copyright &copy; 2007 Simpletex. All Rights Reserved | Designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a></p>
<p id="links"><a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a> | <a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS</abbr></a></p>

flow/templates/fullscreen.html
{% load flow_extras %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Mess Media {{ media.name }}</title>
<style type="text/css">
* { margin:0; padding:0; background-color:#000; text-align:center; }
html, body { height:100%; }
</style>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/prototype.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/AC_Quicktime.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/script.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/tc.js"></script>
</head>

<body>
<script type="text/javascript">// <![CDATA[
	QT_WriteOBJECT_XHTML(
		'{{ player_settings.url }}',
		'100%', '100%',
		'',
		'autoplay', '{{ player_settings.autoplay|default:"true"|lower }}',
		'emb#bgcolor', '{{ player_settings.bgcolor|default:"#000000" }}',
		'align', 'middle',
		'scale', 'aspect',
		'enablejavascript', 'true',
		'showlogo', 'false'
	);
//]]></script>
<noscript>
<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="100%" height="100%">
  <param name="src" value="{{ player_settings.url }}" />
  <param name="autoplay" value="{{ player_settings.autoplay|default:"true"|lower }}" />
  <param name="controller" value="true" />
  <param name="scale" value="{{ player_settings.scale|default:"aspect" }}" />
  <param name="bgcolor" value="#000000" />
  <param name="wmode" value="transparent" />
  <!--[if !IE]>-->
  <object type="video/quicktime" data="{{ player_settings.url }}" width="100%" height="100%">
	<param name="autoplay" value="{{ player_settings.autoplay|lower }}" />
	<param name="controller" value="true" />
	<param name="scale" value="{{ player_settings.scale|default:"aspect" }}" />
	<param name="bgcolor" value="#000000" />
	<param name="wmode" value="transparent" />
  </object>
  <!--<![endif]-->
</object>
</noscript>
</body>
</html>

flow/templates/index.html
{% extends "base.html" %}
{% load flow_extras %}
{% block content %}
<div id="login">
<fieldset>
<legend>Sign In</legend>
{% login %}
</fieldset>
<fieldset>
<legend>Screen a Video</legend>
{% watch_it %}
</fieldset>
</div>
{% endblock %}

flow/templates/media.html
{% extends "media_base.html" %}
{% load flow_extras %}{% load humanize %}{% load comments %}
{% block content %}
{{ block.super }}
<div class="right_links">
	<a href="{{ media.get_file_url }}">download</a> - 
	<a onclick="fullscreen_click('{{ request.get_full_path }}/fullscreen');">fullscreen</a>
</div>
{% player %}

{# if media.display_comments #}{% if 0 %}
	<h3>Comments</h3>
	
	<ul class="comments">
	
		{% render_comment_form for media %}
		
		<a id="show_comment_form">Post a comment</a>
	
		<li id="comment_preview_element" style="opacity: 0.7;"></li>
	
	{% get_comment_list for media as comment_list %}
	{% for comment in comment_list reversed %}
		<li class="form_row comment_row" id="comment_{{ comment.id }}">
			<div class="info">
				<span class="name">{{ comment.user_name }}</span><br />
				{{ comment.submit_date|date:"M j h:i a" }}
			</div>
			<div class="input">
			{% if request.user.is_staff %}
				<div class="actions">
					<form id="delete_comment_{{ comment.id }}" method="post" action="{{ request.path }}">
						<input type="hidden" name="submit" value="delete_comment" />
						<input type="hidden" name="comment_id" value="{{ comment.id }}" />
						<input type="submit" value="delete" />
					</form>
				</div>
			{% endif %}
				{% markup comment.comment media %}
			</div>
		</li>
		<br class="clear" />
	{% endfor %}
	<script type="text/javascript" src="{{ MEDIA_URL }}flow/js/comments.js"></script>
	
	</ul>
{% endif %}
{% endblock %}

flow/templates/media_base.html
{% extends "base.html" %}
{% load flow_extras %}

{% block title %}{{ site.info.title }} | {{ media.title }}{% endblock %}

{% block content %}

<div class="title">
	<h2>{{ media.playlist.name }}</h2>
	<h1>{{ media.title }}</h1>
	{% if media.description %}{{ media.description|escape|linebreaks }}{% endif %}
</div>
{% if user.is_staff %}
<ul class="tabs">
	<li><a {% ifequal view "view" %}class="active"{% else %}href="{{ media.get_url }}"{% endifequal %}>View</a></li>
	<!--li><a {% ifequal view "log" %}class="active"{% else %}href="?v=log"{% endifequal %}>Log</a></li-->
	<li><a {% ifequal view "edit" %}class="active"{% else %}href="{% media_url %}/edit"{% endifequal %}>Edit</a></li>
</ul>
{% endif %}
{% endblock %}

flow/templates/media_edit.html
{% extends "media_base.html" %}
{% load flow_extras %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}flow/css/video_settings.css" />
{% endblock %}

{% block content %}
{{ block.super }}
{% player %}
<form action="" method="post" enctype="multipart/form-data">
<ul>
	<li class="form_row">
		<label>Title:</label>
		<div class="input">{{ media_form.title }}</div>
	</li>
	<li class="form_row">
		<label>Description:</label>
		<div class="input">{{ media_form.description }}</div>
	</li>
	<!--li class="form_row">
		<label>Playlists:</label>
		<div class="input">{{ media_form.playlists }}</div>
	</li-->
	<li class="form_row">
		{{ media_form.playlists_html }}
	</li>
	<li class="form_row">
		{{ media_form.pub_date.label_tag }}
		<div class="input">{{ media_form.pub_date }}</div>
	</li>
	<li class="form_row">
		<label>Poster Image:</label>
		<div class="input">
			<div id="thumb" class="thumb" style="float: left;"><img src="{{ media.get_thumb64_url }}" /></div>
			<div id="thumb_progress" class="thumb" style="float: left;"><img src="{{ MEDIA_URL }}flow/img/roller.gif" style="margin-top:16px;margin-left:24px;" /></div>
			<input type="button" id="thumb_trigger" value="Get Frame" media_id="{{ media.id }}" />
			<input id="id_thumb" name="thumb_file" type="hidden" value="{{ media.thumb }}" />
			<script type="text/javascript">// <![CDATA[
				$('thumb_trigger').observe('click', function(){thumb_trigger('thumb_trigger', '{{ MEDIA_URL }}flow/');});
				$('thumb_progress').hide();
			//]]></script>
			<br style="clear: both;" />
		</div>
	</li>
	<li class="form_row checkbox_row">
		{{ media_form.display_comments }}<label> Display comments</label>
	</li>
	<li class="form_row">
		<label>Display Size:</label>
		<div class="input">
			{{ media_form.display_size }}<span id="custom_display_size">&nbsp; {{ media_form.display_width }} x {{ media_form.display_height }}</span>
		</div>
		<script type="text/javascript">// <![CDATA[
			var initDisplaySize = function() {
				if ($F('id_display_size') == 'C') {
					$('custom_display_size').show();
				}
				else {
					$('custom_display_size').hide();
				}
			}
			initDisplaySize();
			$('id_display_size').observe('change', initDisplaySize);
		//]]></script>
	</li>
	<li class="form_row checkbox_row">
		{{ media_form.displaytc }}<label> Display timecode</label>
	</li>
		<li class="form_row" id="hasedl">
			<label>EDL File:</label>
			<div class="input">
				{{ media.get_edl_origname }} <i>Uploaded {{ media.get_edl_date|date:"M j, Y \a\t P" }}</i>
				<a id="remove_edl" class="delete">Remove</a>
			</div>
		</li>
		<li><ul id="noedl">
		<li class="form_row">
			<label>Start timecode:</label>
			<div class="input">
				<input class="timecode" id="start_tc" name="starttc" value="{{ media.starttc|default:"" }}" type="text" size="11" maxlength="11" />
				{{ media_form.frame_rate }}
				<span class="help"><br />HH:MM:SS:FF</span>
			</div>
		</li>
		<li style="margin: -20px 20px -15px 20px;">--- or ---</li>
		<li class="form_row">
			<label for="edl_file">EDL file:</label>
			<div class="input"><input type="file" id="edl_file" name="edl_file" style="color: #fff;" /></div>
		</li>
		</ul></li>
	<script type="text/javascript">// <![CDATA[
		//tcInit('start', '{{ media.starttc }}');
		initTCInput('start_tc', 'id_frame_rate', '{{ media.starttc }}');
		if ({{ media.edl|yesno:"1,0" }}) {
			$('remove_edl').observe('click', function() {
				// ajax remove edl
				new Ajax.Request('/a/remove_edl', {
					asynchronous: true,
					method: 'get',
					parameters: {
						'media_id': {{ media.id }}
					},
					onSuccess: function(transport) {
						$('hasedl').hide(); $('noedl').show();
					}
				});
			});
			$('hasedl').show(); $('noedl').hide();
		}
		else {
			$('hasedl').hide(); $('noedl').show();
		}
	//]]></script>

	<li class="form_row">
		<input type="submit" name="save" value="Save" />
	</li>
</form>
{% endblock %}

flow/templates/player.html
<div id="player" style="width:{{ player_settings.width }}px; height:{{ player_settings.height|add:"16" }}px;">
<script type="text/javascript">// <![CDATA[
	args = [
		'{{ player_settings.url }}',
		'100%', '100%',
		'',
		'autoplay', '{{ player_settings.autoplay|default:"true"|lower }}',
		'emb#bgcolor', '{{ player_settings.bgcolor|default:"#000000" }}',
		'scale', '{{ player_settings.scale|default:"tofit" }}',
		'align', 'middle',
		'enablejavascript', 'true',
		'showlogo', 'false'
	]
	QT_WriteOBJECT_XHTML.apply(this, args);
	var player = $('player').get_qtplayer();
//]]></script>
<noscript>
<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="{{ player_settings.width|default:"320" }}" height="{{ player_settings.height|default:"240"|add:"16" }}">
  <param name="src" value="{{ player_settings.url }}" />
  <param name="autoplay" value="{{ player_settings.autoplay|default:"true"|lower }}" />
  <param name="controller" value="true" />
  <param name="scale" value="{{ player_settings.scale|default:"aspect" }}" />
  <param name="bgcolor" value="#000000" />
  <param name="wmode" value="transparent" />
  <!--[if !IE]>-->
  <object type="video/quicktime" data="{{ player_settings.url }}" width="{{ player_settings.width }}" height="{{ player_settings.height|add:"16" }}">
	<param name="autoplay" value="{{ player_settings.autoplay|lower }}" />
	<param name="controller" value="true" />
	<param name="scale" value="{{ player_settings.scale }}" />
	<param name="bgcolor" value="#000000" />
	<param name="wmode" value="transparent" />
  </object>
  <!--<![endif]-->
</object>
</noscript>
<div id='debug' style="position: absolute; top: 0; left: 0;"></div>
</div>

{% if player_settings.timecode %}
<div id="player_wrap" style="width:{{ player_settings.width }}px;">
{% if media.edl %}
<script type="text/javascript" src="{{ media.edl.url }}"></script>
<script type="text/javascript">// <![CDATA[
var tc_calc = new TimecodeCalc(edl, {{ media.get_fps }});
//]]></script>
{% else %}
<script type="text/javascript">// <![CDATA[
var start_tc = '{{ media.starttc }}';
var tc_calc = new TimecodeCalc(start_tc, {{ media.get_fps }});
//]]></script>
{% endif %}

	<span id="timecode" class="numeric">&nbsp;</span>
	<script type="text/javascript">// <![CDATA[
		new PeriodicalExecuter( function() {
			var offset = player.getOffset();
			var update_text = '';
			var tc = '';
			if (tc_calc.edl) {
				var edit = tc_calc.editFromOffset(offset);
				var tape = (edit) ? edit['src'] : 'None';
				tc = tc_calc.timecodeFromOffset(offset, edit);
				if ((player.getRate() != 0) && (edit)) {
					tc = tc.substr(0, 9) + '--';
				}
				update_text = tape + ' - ' + tc;
			}
			else {
				var tc = tc_calc.timecodeFromOffset(offset);
				if (player.getRate() != 0) {
					tc = tc.substr(0, 9) + '--';
				}
				update_text = tc;
			}
			$('timecode').update(update_text);
		}, .5 );
	//]]></script>
</div>
<!--a onclick="javascript:alert(player.getQtMatrix())">get matrix</a>
<a onclick="javascript:alert(player.getRectangle())">get rectangle</a-->
{% endif %}

{% ifequal player_settings.scale "1" %}
<script type="text/javascript">// <![CDATA[
new PeriodicalExecuter(function(pe) {
	var matrix = player.getQtMatrix();
	if (matrix) {
		var rect = player.getQtRectangle();
		if (matrix[0][0] != 1) {
			var width = (rect[2]-rect[0])+'px';
			$('player', 'player_wrap').each(function(e) {e.setWidth(width);});
		}
		if (matrix[1][1] != 1) {
			$('player').setHeight((16+rect[3]-rect[1])+'px');
		}
		pe.stop();
	}
}, 0.1);
//]]></script>
{% endifequal %}

flow/templates/playlist.html
{% extends "playlist_base.html" %}
{% load flow_extras %}{% load humanize %}{% load comments %}
{% block content %}
{{ block.super }}
{% if not playlist.no_settings %}
<div class="right_links">
	<a href="itpc://{{ request.get_host }}{% url flow.views.feed playlist.path %}">subscribe via iTunes</a>
</div>
{% endif %}
{% media_list_as_ul request playlist.medias playlist %}
{% endblock %}

flow/templates/watch_it.html
<form method="post" action="/a/watch_it">
	<p><label for="id_media">Video ID </label><input type="text" id="id_media" name="media" size="15" /></p>
	<p><input type="submit" value="Watch It" /></p>
</form>